version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "bms-lambda"
s3_bucket = "bms-lambda-deployment-1765969818"
s3_prefix = "bms-lambda"
region = "ap-south-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = false
parameter_overrides = [
  "DatabaseHost=bookmyshow.cxwyaqu60aes.ap-south-1.rds.amazonaws.com",
  "DatabasePort=5432", 
  "DatabaseName=bms",
  "DatabaseUser=postgres",
  "DatabasePassword=2kTqQ7Mcl054kELxa955",
  "RedisHost=redis-15866.crce182.ap-south-1-1.ec2.cloud.redislabs.com",
  "RedisPort=15866"
]

[default.build.parameters]
use_container = true